import { caroKannCourse } from "@/lib/content/caro-kann";
import type { CourseSpec } from "@/lib/content/types";

/**
 * Course registry (PRD §7: new openings are added without touching app code).
 *
 * In production this list is generated by the offline pipeline in PRD §47–§49
 * and written straight to PostgreSQL; during development it is a plain array so
 * `npm run db:seed` can rebuild the whole content set from source.
 */
export const courseSpecs: CourseSpec[] = [caroKannCourse];

/** Deterministic course ids so reseeding never orphans user progress. */
export function courseIdFor(slug: string): string {
  return `course:${slug}`;
}

export function findCourseSpec(slug: string): CourseSpec | undefined {
  return courseSpecs.find((spec) => spec.slug === slug);
}
